-- ============================================================
-- SMLS RESET & SEED SCRIPT (FIXED - v4)
-- ============================================================
-- Clears all transactional data: Requirements, POs, Deliveries,
-- QC, Material Issues, Recoveries, and Transactions.
-- Then adds new fresh data for testing.
-- ============================================================

BEGIN;

-- 1. TRUNCATE ALL TRANSACTIONAL & PROCESS TABLES
-- We use CASCADE to clean child tables automatically
TRUNCATE 
  public.workflow_history,
  public.scrap_logs,
  public.recoveries,
  public.inventory_transactions,
  public.inventory_pins,
  public.qc_defects,
  public.qc_inspections,
  public.delivery_items,
  public.deliveries,
  public.po_items,
  public.purchase_orders,
  public.requirement_items,
  public.requirements,
  public.material_issues,
  public.vendors,
  public.vendor_contacts
CASCADE;

-- 2. RESET SEQUENCES 
-- (The stored procedures handle ref increments, but we could reset seq_counters if we wanted the IDs to start from 000001 again)
UPDATE public.seq_counters SET last_val = 0;
ALTER SEQUENCE public.pin_seq RESTART WITH 1;

-- 3. SEED NEW VENDORS
INSERT INTO public.vendors (id, code, name, email, is_approved)
VALUES 
  ('00000000-0000-0000-0000-000000000010', 'V-MGS',  'Maritime Global Spares', 'orders@mgs-global.com', true),
  ('00000000-0000-0000-0000-000000000020', 'V-NAV',  'Navis Tooling Co.',      'sales@navis.com',       true),
  ('00000000-0000-0000-0000-000000000030', 'V-HYD',  'Hydraulic Solutions Ltd', 'contact@hydrosl.com',   true);

-- 4. ENSURE A LOCATION EXISTS
INSERT INTO public.store_locations (id, code, name, warehouse, zone)
VALUES ('00000000-0000-0000-0000-000000000001', 'DECK-A1', 'Main Deck Alpha', 'Central Warehouse', 'Zone A')
ON CONFLICT (id) DO NOTHING;

-- 5. SEED INVENTORY PINS (Linked to Location)
-- PIN numbers will be auto-generated by trigger (PIN-000001, etc.)
INSERT INTO public.inventory_pins (id, description, category, unit, location_id, item_category, status, origin_type)
VALUES
  (uuid_generate_v4(), 'Shackle High-Tensile 25mm', 'Rigging',     'pcs', '00000000-0000-0000-0000-000000000001', 'returnable', 'approved'::public.item_status, 'opening_balance'),
  (uuid_generate_v4(), 'O-Ring Kit Universal',      'Consumables', 'box', '00000000-0000-0000-0000-000000000001', 'consumable', 'approved'::public.item_status, 'opening_balance'),
  (uuid_generate_v4(), 'Lube Oil SAE 40 (20L)',     'Oil',         'tin', '00000000-0000-0000-0000-000000000001', 'consumable', 'approved'::public.item_status, 'opening_balance'),
  (uuid_generate_v4(), 'LED Floodlight 50W',        'Electrical',  'pcs', '00000000-0000-0000-0000-000000000001', 'returnable', 'approved'::public.item_status, 'opening_balance');

-- 6. ADD SOME OPEN STOCK VIA TRANSACTIONS
-- (Find pins by description since PIN numbers are trigger-generated)
WITH pin1 AS (SELECT id FROM public.inventory_pins WHERE description = 'Shackle High-Tensile 25mm'),
     pin2 AS (SELECT id FROM public.inventory_pins WHERE description = 'O-Ring Kit Universal'),
     adm  AS (SELECT id FROM public.profiles LIMIT 1)
INSERT INTO public.inventory_transactions (pin_id, transaction_type, quantity, actor_id, notes)
SELECT pin1.id, 'receipt'::public.transaction_type, 10, adm.id, 'Opening stock for flow test' FROM pin1 cross join adm
UNION ALL
SELECT pin2.id, 'receipt'::public.transaction_type, 5,  adm.id, 'Opening stock for flow test' FROM pin2 cross join adm;

COMMIT;
