import type { Role } from "@/lib/auth/roles";
import { ROLES } from "@/lib/auth/roles";

export type Action =
  | "create" | "read" | "update" | "delete" | "approve" | "reject"
  | "export" | "import" | "manage_users";

export type Resource =
  | "requirement" | "approval" | "vendor" | "purchase_order"
  | "payment" | "delivery" | "receiving" | "qc_inspection"
  | "qc_return" | "inventory" | "pin" | "issue" | "recovery"
  | "report" | "chatbot" | "settings";

type PermissionMatrix = Partial<Record<Resource, Action[]>>;

export const PERMISSIONS: Record<Role, PermissionMatrix> = {
  [ROLES.SUPER_ADMIN]: {
    requirement: ["create","read","update","delete","approve","reject","export"],
    approval: ["create","read","update","delete","approve","reject"],
    vendor: ["create","read","update","delete","export","import"],
    purchase_order: ["create","read","update","delete","approve","reject","export"],
    payment: ["create","read","update","delete","export"],
    delivery: ["create","read","update","delete","export"],
    receiving: ["create","read","update","delete"],
    qc_inspection: ["create","read","update","delete"],
    qc_return: ["create","read","update","delete"],
    inventory: ["create","read","update","delete","export"],
    pin: ["create","read","update","delete"],
    issue: ["create","read","update","delete","approve","reject"],
    recovery: ["create","read","update","delete","approve","reject"],
    report: ["read","export"],
    chatbot: ["read"],
    settings: ["read","update","manage_users"],
  },
  [ROLES.ADMIN]: {
    requirement: ["create","read","update","approve","reject","export"],
    approval: ["create","read","update","approve","reject"],
    vendor: ["create","read","update","export","import"],
    purchase_order: ["create","read","update","approve","reject","export"],
    payment: ["create","read","update","export"],
    delivery: ["create","read","update","export"],
    receiving: ["create","read","update"],
    qc_inspection: ["create","read","update"],
    qc_return: ["create","read","update"],
    inventory: ["create","read","update","export"],
    pin: ["create","read","update"],
    issue: ["create","read","update","approve","reject"],
    recovery: ["create","read","update","approve","reject"],
    report: ["read","export"],
    chatbot: ["read"],
    settings: ["read","update"],
  },
  [ROLES.PROCUREMENT_MANAGER]: {
    requirement: ["create","read","update","approve","reject"],
    approval: ["read","approve","reject"],
    vendor: ["create","read","update","export"],
    purchase_order: ["create","read","update","approve","reject"],
    payment: ["create","read","update"],
    delivery: ["create","read","update"],
    receiving: ["read"],
    qc_inspection: ["read"],
    qc_return: ["read"],
    inventory: ["read"],
    pin: ["read"],
    issue: ["read"],
    recovery: ["read"],
    report: ["read","export"],
    chatbot: ["read"],
    settings: ["read"],
  },
  [ROLES.PROCUREMENT_OFFICER]: {
    requirement: ["create","read","update"],
    approval: ["read"],
    vendor: ["read","update"],
    purchase_order: ["create","read","update"],
    payment: ["create","read","update"],
    delivery: ["create","read","update"],
    receiving: ["read"],
    qc_inspection: ["read"],
    qc_return: ["read"],
    inventory: ["read"],
    pin: ["read"],
    issue: ["read"],
    recovery: ["read"],
    report: ["read"],
    chatbot: ["read"],
    settings: ["read"],
  },
  [ROLES.STORE_MANAGER]: {
    requirement: ["read"],
    approval: ["read"],
    vendor: ["read"],
    purchase_order: ["read"],
    payment: ["read"],
    delivery: ["read"],
    receiving: ["create","read","update"],
    qc_inspection: ["read"],
    qc_return: ["create","read","update"],
    inventory: ["create","read","update","export"],
    pin: ["create","read","update"],
    issue: ["create","read","update","approve"],
    recovery: ["create","read","update","approve"],
    report: ["read","export"],
    chatbot: ["read"],
    settings: ["read"],
  },
  [ROLES.STORE_KEEPER]: {
    requirement: ["read"],
    approval: ["read"],
    vendor: ["read"],
    purchase_order: ["read"],
    payment: ["read"],
    delivery: ["read"],
    receiving: ["create","read","update"],
    qc_inspection: ["read"],
    qc_return: ["read"],
    inventory: ["read","update"],
    pin: ["read","update"],
    issue: ["create","read","update"],
    recovery: ["read"],
    report: ["read"],
    chatbot: ["read"],
    settings: ["read"],
  },
  [ROLES.QC_INSPECTOR]: {
    requirement: ["read"],
    approval: ["read"],
    vendor: ["read"],
    purchase_order: ["read"],
    payment: ["read"],
    delivery: ["read"],
    receiving: ["read"],
    qc_inspection: ["create","read","update"],
    qc_return: ["create","read","update"],
    inventory: ["read"],
    pin: ["read"],
    issue: ["read"],
    recovery: ["read"],
    report: ["read"],
    chatbot: ["read"],
    settings: ["read"],
  },
  [ROLES.ENGINEER]: {
    requirement: ["create","read","update"],
    approval: ["read"],
    vendor: ["read"],
    purchase_order: ["read"],
    payment: ["read"],
    delivery: ["read"],
    receiving: ["read"],
    qc_inspection: ["read"],
    qc_return: ["read"],
    inventory: ["read"],
    pin: ["read"],
    issue: ["create","read","update"],
    recovery: ["read"],
    report: ["read"],
    chatbot: ["read"],
    settings: ["read"],
  },
  [ROLES.APPROVER]: {
    requirement: ["read","approve","reject"],
    approval: ["read","approve","reject"],
    vendor: ["read"],
    purchase_order: ["read","approve","reject"],
    payment: ["read"],
    delivery: ["read"],
    receiving: ["read"],
    qc_inspection: ["read"],
    qc_return: ["read"],
    inventory: ["read"],
    pin: ["read"],
    issue: ["read","approve","reject"],
    recovery: ["read","approve","reject"],
    report: ["read"],
    chatbot: ["read"],
    settings: ["read"],
  },
  [ROLES.VIEWER]: {
    requirement: ["read"],
    approval: ["read"],
    vendor: ["read"],
    purchase_order: ["read"],
    payment: ["read"],
    delivery: ["read"],
    receiving: ["read"],
    qc_inspection: ["read"],
    qc_return: ["read"],
    inventory: ["read"],
    pin: ["read"],
    issue: ["read"],
    recovery: ["read"],
    report: ["read"],
    chatbot: ["read"],
    settings: ["read"],
  },
};
